# Generated by Django 4.2.18 on 2026-01-03 10:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_age_person_class_name_person_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='image',
            field=models.ImageField(upload_to=core.models.get_face_image_path),
        ),
    ]
