# Generated by Django 4.2.18 on 2026-01-05 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_missinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missinglog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
