# Generated by Django 4.2.18 on 2026-01-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_missinglog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='missinglog',
            name='location',
            field=models.CharField(default='Classroom', max_length=50),
        ),
        migrations.AddField(
            model_name='missinglog',
            name='status',
            field=models.CharField(default='Missing', max_length=50),
        ),
    ]
